# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ReceiverSetting(object):
    def setupUi(self, ReceiverSetting):
        ReceiverSetting.setObjectName("ReceiverSetting")
        ReceiverSetting.setFixedSize(601, 434)
        self.layoutWidget = QtWidgets.QWidget(ReceiverSetting)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 360, 256, 46))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.checkBox_3 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_3.setObjectName("checkBox_3")
        self.horizontalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_4.setObjectName("checkBox_4")
        self.horizontalLayout.addWidget(self.checkBox_4)
        self.checkBox_5 = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_5.setObjectName("checkBox_5")
        self.horizontalLayout.addWidget(self.checkBox_5)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label = QtWidgets.QLabel(ReceiverSetting)
        self.label.setGeometry(QtCore.QRect(30, 30, 256, 16))
        self.label.setObjectName("label")
        self.line = QtWidgets.QFrame(ReceiverSetting)
        self.line.setGeometry(QtCore.QRect(220, 30, 81, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(ReceiverSetting)
        self.line_2.setGeometry(QtCore.QRect(290, 40, 20, 281))
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_4 = QtWidgets.QFrame(ReceiverSetting)
        self.line_4.setGeometry(QtCore.QRect(10, 40, 20, 281))
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.line_5 = QtWidgets.QFrame(ReceiverSetting)
        self.line_5.setGeometry(QtCore.QRect(20, 310, 281, 20))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.layoutWidget1 = QtWidgets.QWidget(ReceiverSetting)
        self.layoutWidget1.setGeometry(QtCore.QRect(30, 60, 258, 246))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.treeWidget = QtWidgets.QTreeWidget(self.layoutWidget1)
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsAutoTristate)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsDropEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled|QtCore.Qt.ItemIsAutoTristate)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsDropEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsAutoTristate)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setFlags(QtCore.Qt.ItemIsSelectable | QtCore.Qt.ItemIsDragEnabled | QtCore.Qt.ItemIsDropEnabled | QtCore.Qt.ItemIsUserCheckable | QtCore.Qt.ItemIsEnabled | QtCore.Qt.ItemIsAutoTristate)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1.setCheckState(0, QtCore.Qt.Unchecked)
        self.verticalLayout_2.addWidget(self.treeWidget)
        self.line_3 = QtWidgets.QFrame(ReceiverSetting)
        self.line_3.setGeometry(QtCore.QRect(310, 0, 20, 441))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_3 = QtWidgets.QLabel(ReceiverSetting)
        self.label_3.setGeometry(QtCore.QRect(340, 30, 121, 16))
        self.label_3.setObjectName("label_3")
        self.layoutWidget2 = QtWidgets.QWidget(ReceiverSetting)
        self.layoutWidget2.setGeometry(QtCore.QRect(360, 380, 191, 26))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.layoutWidget3 = QtWidgets.QWidget(ReceiverSetting)
        self.layoutWidget3.setGeometry(QtCore.QRect(340, 60, 241, 284))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_3.addWidget(self.lineEdit)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout_3.addWidget(self.lineEdit_2)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.verticalLayout_3.addWidget(self.lineEdit_3)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_3.addWidget(self.label_8)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.verticalLayout_3.addWidget(self.lineEdit_5)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_3.addWidget(self.label_9)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.verticalLayout_3.addWidget(self.lineEdit_6)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_3.addWidget(self.label_6)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_3.addWidget(self.lineEdit_4)

        self.retranslateUi(ReceiverSetting)
        QtCore.QMetaObject.connectSlotsByName(ReceiverSetting)

    def retranslateUi(self, ReceiverSetting):
        _translate = QtCore.QCoreApplication.translate
        ReceiverSetting.setWindowTitle(_translate("ReceiverSetting", "Open Data Feeds Receiver"))
        self.label_2.setText(_translate("ReceiverSetting", "Options："))
        self.checkBox_3.setText(_translate("ReceiverSetting", "Save to SQL"))
        self.checkBox_4.setText(_translate("ReceiverSetting", "View"))
        self.checkBox_5.setText(_translate("ReceiverSetting", "Durable"))
        self.label.setText(_translate("ReceiverSetting", "Select the data to be received ："))
        self.treeWidget.headerItem().setText(0, _translate("ReceiverSetting", "Network Rail Open Data Feeds"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("ReceiverSetting", "TD"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("ReceiverSetting", "All area"))
        self.treeWidget.topLevelItem(0).child(1).setText(0, _translate("ReceiverSetting", "Derby"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("ReceiverSetting", "Train Movement"))
        self.treeWidget.topLevelItem(1).child(0).setText(0, _translate("ReceiverSetting", "\"0001\": \"activation\""))
        self.treeWidget.topLevelItem(1).child(1).setText(0, _translate("ReceiverSetting", "\"0002\": \"cancellation\""))
        self.treeWidget.topLevelItem(1).child(2).setText(0, _translate("ReceiverSetting", "\"0003\": \"movement\""))
        self.treeWidget.topLevelItem(1).child(3).setText(0, _translate("ReceiverSetting", "\"0004\": \"_unidentified\""))
        self.treeWidget.topLevelItem(1).child(4).setText(0, _translate("ReceiverSetting", "\"0005\": \"reinstatement\""))
        self.treeWidget.topLevelItem(1).child(5).setText(0, _translate("ReceiverSetting", "\"0006\": \"origin change\""))
        self.treeWidget.topLevelItem(1).child(6).setText(0, _translate("ReceiverSetting", "\"0007\": \"identity change\""))
        self.treeWidget.topLevelItem(1).child(7).setText(0, _translate("ReceiverSetting", "\"0008\": \"_location change\""))
        self.treeWidget.topLevelItem(2).setText(0, _translate("ReceiverSetting", "VSTP"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("ReceiverSetting", "RTPPM"))
        self.treeWidget.topLevelItem(3).child(0).setText(0, _translate("ReceiverSetting", "NationalPage_Sector"))
        self.treeWidget.topLevelItem(3).child(1).setText(0, _translate("ReceiverSetting", "NationalPage_Operator"))
        self.treeWidget.topLevelItem(3).child(2).setText(0, _translate("ReceiverSetting", "OOCPage"))
        self.treeWidget.topLevelItem(3).child(3).setText(0, _translate("ReceiverSetting", "OperatorPage"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.label_3.setText(_translate("ReceiverSetting", "Set SQL infomation:"))
        self.pushButton.setText(_translate("ReceiverSetting", "Start"))
        self.pushButton_2.setText(_translate("ReceiverSetting", "Back"))
        self.label_4.setText(_translate("ReceiverSetting", "sql_username:"))
        self.label_5.setText(_translate("ReceiverSetting", "sql_password:"))
        self.label_7.setText(_translate("ReceiverSetting", "schema_name:"))
        self.label_8.setText(_translate("ReceiverSetting", "database_name:"))
        self.label_9.setText(_translate("ReceiverSetting", "sql_host"))
        self.label_6.setText(_translate("ReceiverSetting", "port:"))

    def click_success1(self):
        sql_info = self.get_sql_info()
        get_options = self.get_options()
        feeds_list, td_list, mvt_list, rtppm_list = self.get_subscribed_topic()
        self._signal2.emit(sql_info, get_options, feeds_list, td_list, mvt_list, rtppm_list, self.Email, self.password)
        self.Saving_view.show()

    def get_sql_info(self):
        sql_info = {}
        sql_info['sql_username'] = self.lineEdit.text()
        sql_info['sql_password'] = self.lineEdit_2.text()
        sql_info['schema_name'] = self.lineEdit_3.text()
        sql_info['database_name'] = self.lineEdit_5.text()
        sql_info['sql_host'] = self.lineEdit_6.text()
        sql_info['port'] = self.lineEdit_4.text()
        return sql_info

    def get_subscribed_topic(self):
        feeds_list = []
        td_list = []
        mvt_list = []
        rtppm_list = []
        n = self.treeWidget.topLevelItemCount()
        for i in range(0, n):
            item = self.treeWidget.topLevelItem(i)
            text = item.text(0)
            count = item.childCount()
            if count == 0 and item.checkState(0) == 2:
                feeds_list.append(text)
            if count != 0:
                for j in range(0, count):
                    string = item.child(j).text(0)
                    if item.child(j).checkState(0) == 2:
                        feeds_list.append(text)
                        if text == 'TD':
                            td_list.append(string)
                        if text == 'Train Movement':
                            mvt_list.append(string)
                        if text == 'RTPPM':
                            rtppm_list.append(string)
        feeds_list = list(set(feeds_list))
        return feeds_list, td_list, mvt_list, rtppm_list

    def get_options(self):
        option_dict = {
            'Save_to_SQL': False,
            'View': False,
            'Durable': False
        }
        if self.checkBox_3.checkState() == 2:
            option_dict['Save_to_SQL'] = True
        if self.checkBox_4.checkState() == 2:
            option_dict['View'] = True
        if self.checkBox_5.checkState() == 2:
            option_dict['Durable'] = True
        return option_dict

    def get_feeds_account(self, Email, password):
        self.Email = Email
        self.password = password

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ReceiverSetting = QtWidgets.QWidget()
    ui = Ui_ReceiverSetting()
    ui.setupUi(ReceiverSetting)
    ReceiverSetting.show()
    sys.exit(app.exec_())
